CHORD_DIM = 48
HIDDEN_DIM = 256
LATENT_DIM = 64
NUM_LAYERS = 2
DROPOUT = 0.2
BIDIRECTIONAL_ENCODER = True

BATCH_SIZE = 128
LEARNING_RATE = 5e-4
BETA = 1.0
FREE_BITS = 1.5
MAX_EPOCHS = 40
PATIENCE = 7
GRAD_CLIP = 5.0
TEACHER_FORCING_RATIO = 0.5

WORD_DROPOUT = 0.3
KL_WARMUP_EPOCHS = 10

LAMBDA_COH = 0.1
LAMBDA_TENS = 0.05
LAMBDA_MOV = 0.1

LOG_DIR = 'runs/cvae'
CHECKPOINT_DIR = 'checkpoints'

KL_COLLAPSE_THRESHOLD = 0.001
KL_COLLAPSE_PATIENCE = 2
RECON_CHEAT_THRESHOLD = 0.001
COH_WORSEN_PATIENCE = 3
