CHORD_DIM = 48
HIDDEN_DIM = 256
DECODER_HIDDEN_DIM = 256
LATENT_DIM = 64
NUM_LAYERS = 2
DROPOUT = 0.2
BIDIRECTIONAL_ENCODER = True

BATCH_SIZE = 256
LEARNING_RATE = 5e-4
BETA = 0.01
FREE_BITS = 1.0
MAX_EPOCHS = 30
PATIENCE = 10
GRAD_CLIP = 5.0
TEACHER_FORCING_RATIO = 1.0

WORD_DROPOUT = 0.7
COND_DROPOUT = 0.3
ENCODER_COND_DROPOUT = 0.0
KL_WARMUP_EPOCHS = 2
KL_CYCLE = 10

SCHEDULED_SAMPLING_START = 0.5
SCHEDULED_SAMPLING_END = 0.10
SCHEDULED_SAMPLING_EPOCHS = 5

LAMBDA_COH = 0.1
LAMBDA_TENS = 0.0
LAMBDA_MOV = 0.0

LOG_DIR = 'runs/cvae'
CHECKPOINT_DIR = 'checkpoints'

KL_COLLAPSE_THRESHOLD = 0.001
KL_COLLAPSE_PATIENCE = 2
RECON_CHEAT_THRESHOLD = 0.001
COH_WORSEN_PATIENCE = 3
ACTIVE_UNITS_THRESHOLD = 0.15
# NOTE: kl_real in latent_stats is TOTAL per sample (sum over all dims)
# With β=0.01, healthy KL_real ~10-50 (was ~500-600 with β=0)
# Threshold 5 catches actual collapse (KL_real ~0-1)
KL_REAL_THRESHOLD = 5.0
